### ISSUE TITLE
How can I ref another yaml

### ISSUE THREAD

**Issue by liao-chenyi-ca** [rohit-gohri/redocusaurus#105]
Hi Team,

Thank you provide this plugin for us.
Just a question.
How can I ref. another yaml file just like,
```
requestBodies:
    Pet:
      content:
        application/json:
          schema:
            allOf:
            - $ref: 'other.yaml#/components/schemas/Pet'
```
I tried it and there was no error.
But it didn't show on the web page.

Thank you very much!
