### ISSUE TITLE
Can't retrieve spec from a private Nexus repository

### ISSUE THREAD

**Issue by aleksimo** [rohit-gohri/redocusaurus#252]
Hello there, 

I am trying to integrate an API spec from a Nexus repo via Redocusaurus.
In Docusaurus, I have the following config:

```json
'redocusaurus',
      {
        // Plugin Options for loading OpenAPI files
        specs: [
          {
            id: 'api',
            config: 'redocly.yaml',
            spec: 'https://repository.mycompany.com/content/groups/bla-bla/0.0.9/openapi.yaml',
            route: '/api/',
          },
}
```

As the Nexus repo requires authentication, in the root, I have added **redocly.yaml** with the `resolve` object and provided credentials. But this solution still results in error 401.

```yaml
resolve:
  http:
    headers:
      - matches: https://repository.mycompany.com/**
        name: Authorization
        envVariable: Basic SOMEKEY
```
The logs from `NODE_DEBUG=http,http2 npm start` show that the header is empty and that the config is not attached. Though, when creating both  **redocly.yaml** and **.redocly.yaml** in the project's root, I get the anticipated error.

What can be the problem here?
Thank you in advance.
