### ISSUE TITLE
Sidebar scrolls under navbar

### ISSUE THREAD

**Issue by notAreYouScared** [rohit-gohri/redocusaurus#360]
![image](https://img.areyouscared.dev/HExe2/xeralONU10.gif/raw)

This happens with both search-bar enabled and disabled. 

Pulling and Building [This Branch](https://github.com/pelican-dev/docs/tree/api-doc-2) will recreate the issue.

**Comment by tkenda** [comment]
Create a file redocly.yaml with this configuration:

```yaml
extends:
  - recommended

rules:
  no-unused-components: error

theme:
  openapi:
    requiredPropsFirst: true
    noAutoAuth: true
    hideDownloadButton: true
    onlyRequiredInSamples: true
    nativeScrollbars: true
    scrollYOffset: 60
    theme:
      colors:
        primary:
          main: '#32329f'
```

and then setup presets in docusarus.config.ts

```js
presets: [
  [
    "classic",
    {
      docs: {
        sidebarPath: "./sidebars.ts",
      },
      theme: {
        customCss: "./src/css/custom.css",
      },
    } satisfies Preset.Options,
  ],
  [
    "redocusaurus",
    {
      config: path.join(__dirname, 'redocly.yaml'),
      specs: [
        {
          spec: "./specs/swagger.json",
          route: "/api/",
        },
      ],
      theme: {
        primaryColor: "#1890ff",
      },
    },
  ] satisfies Redocusaurus.PresetEntry,
]
```

This will solve your issue!

**Comment by robbieaverill** [comment]
The salient part of the example above is this:
```yaml
extends:
  - recommended

theme:
  openapi:
    scrollYOffset: 600
```

THanks @tkenda 👍
