### ISSUE TITLE
Incorrect implementation of `prefixCssSelectors`

### ISSUE THREAD

**Issue by a-ignatov-parc** [rohit-gohri/redocusaurus#377]
The current implementation of `prefixCssSelectors` ([ref](https://github.com/rohit-gohri/redocusaurus/blob/5d0aaf3d49245bbac64e18bd8f81222f5ab46951/packages/docusaurus-theme-redoc/src/theme/Redoc/ServerStyles.tsx#L12-L51)) doesn't properly handle prefixing css rules in media queries, which results in broken layouts during the initial render until the hydration is finished and styles are re-rendered with JS.

<img width="373" alt="image" src="https://github.com/user-attachments/assets/aae2d7c7-7774-49d6-8b19-355d35e0ffe8">

Here's an example of how the current implementation handles media queries

```css
html:not([data-theme='dark']) .jdZmzL {
    z-index: 1;
    position: relative;
    overflow: hidden;
    width: calc(100% - 300px);
    contain: layout;
}

@media print,html:not([data-theme='dark']) screen and (max-width: 50rem) {
    .jdZmzL {
        width:100%;
    }
}
```

The issue is that the `jdZmzL` class in the media query has a lower specificity than the initial one, which results in ignoring its styles.

<img width="884" alt="image" src="https://github.com/user-attachments/assets/5bf67240-3f36-4bdb-8fb8-b30e49f283f4">

The correct result would be as follows

```css
html:not([data-theme='dark']) .jdZmzL {
    z-index: 1;
    position: relative;
    overflow: hidden;
    width: calc(100% - 300px);
    contain: layout;
}

@media print, screen and (max-width: 50rem) {
    html:not([data-theme='dark']) .jdZmzL {
        width:100%;
    }
}
```

<img width="881" alt="image" src="https://github.com/user-attachments/assets/2331cb67-07c1-4f28-8cf2-ed264486cea3">
