### ISSUE TITLE
Regression: Example header less readable color in light mode

### ISSUE THREAD

**Issue by joshtemple** [rohit-gohri/redocusaurus#65]
Previously, the following header "Response samples" was white in both dark and light mode. In 0.4.4 it switches to black text in light mode which is not very readable.

![Screen Shot 2021-06-29 at 10 52 39 PM](https://user-images.githubusercontent.com/8672171/123894827-dcbb8f80-d92c-11eb-859b-681846f89a9d.png)

**Comment by rohit-gohri** [comment]
Thanks for reporting this! Probably caused by #60 I think

**Comment by inacho** [comment]
Removing the following styles fixes the issue:

```css
.redocusaurus h2,
.redocusaurus h3,
.redocusaurus h4 {
  color: var(--ifm-font-color-base);
}
```

@rohit-gohri Do you think it's ok to completely remove those styles?
